from django.urls import path
from .views import (
    InfluencerListCreateView, 
    InfluencerDetailView, 
    CampaignListCreateView, 
    CampaignDetailView,
    BookingListCreateView, 
    search_influencers, 
    confirm_booking, 
    book_influencer, 
    update_booking_status, 
    login_view, 
    get_notifications, 
    campaign_matches,
    influencer_profile,
    InfluencerUpdateView,
    register_view,
    match_influencers,
    booking_detail,
    create_booking,
    admin_list_campaigns,
    admin_delete_campaign,
    admin_list_influencers,
    admin_add_influencer,
    admin_edit_influencer,
    admin_delete_influencer,
    admin_list_bookings,
    admin_update_booking_status,
    admin_booking_detail,
    admin_get_campaign_details,
    initiate_payment,
    complete_payment,
    get_approved_bookings,
    influencer_dashboard,
    influencer_bookings,
    influencer_dashboard_stats,
    debug_influencers,
    influencer_profile_setup,
    influencer_profile_status,
    test_api,
    influencer_my_profile,
    influencer_profile_update,
    test_auth,
    influencer_campaigns,
    accept_campaign,
    decline_campaign,
    campaign_assets,
    quick_add_influencer,
    admin_login_view,
    upload_influencers_excel
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('influencers/', InfluencerListCreateView.as_view(), name='influencer-list'),
    path('influencers/<int:pk>/', InfluencerDetailView.as_view(), name='influencer-detail'),
    path('campaigns/', CampaignListCreateView.as_view(), name='campaign-list'),
    path('campaigns/<int:pk>/', CampaignDetailView.as_view(), name='campaign-detail'),
    path('campaigns/<int:campaign_id>/matches/', campaign_matches, name='campaign-matches'),
    path('campaigns/<int:campaign_id>/search-influencers/', search_influencers, name='search-influencers'),
    path('bookings/', BookingListCreateView.as_view(), name='bookings'),
    path('bookings/<int:booking_id>/confirm/', confirm_booking, name='confirm_booking'),
    path('bookings/<int:booking_id>/update-status/', update_booking_status, name='update_booking_status'),
    path('auth/login/', login_view, name='login'),
    path('influencer-notifications/<int:influencer_id>/', get_notifications, name='influencer-notifications'),
    path('influencers/<int:influencer_id>/profile/', influencer_profile, name='influencer-profile'),
    path('influencers/<int:pk>/update/', InfluencerUpdateView.as_view(), name='influencer-update'),
    path('auth/register/', register_view, name='register'),
    path('campaigns/<int:campaign_id>/match-influencers/', match_influencers, name='match-influencers'),
    path('bookings/<int:booking_id>/', booking_detail, name='booking-detail'),
    path('bookings/create/', create_booking, name='create-booking'),
    path('admin/campaigns/', admin_list_campaigns, name='admin-campaigns'),
    path('admin/campaigns/<int:pk>/delete/', admin_delete_campaign, name='admin-delete-campaign'),
    path('admin/influencers/list/', admin_list_influencers, name='admin-list-influencers'),
    path('admin/influencers/add/', admin_add_influencer, name='admin-add-influencer'),
    path('admin/influencers/<int:pk>/edit/', admin_edit_influencer, name='admin-edit-influencer'),
    path('admin/influencers/<int:pk>/delete/', admin_delete_influencer, name='admin-delete-influencer'),
    path('admin/bookings/', admin_list_bookings, name='admin-bookings'),
    path('admin/bookings/<int:pk>/update-status/', admin_update_booking_status, name='admin-update-booking'),
    path('admin/bookings/<int:booking_id>/detail/', admin_booking_detail, name='admin-booking-detail'),
    path('admin/campaigns/<int:pk>/', admin_get_campaign_details, name='admin-campaign-details'),
    path('payments/initiate/<int:booking_id>/', initiate_payment, name='initiate-payment'),
    path('payments/complete/<int:payment_id>/', complete_payment, name='complete-payment'),
    path('bookings/approved-pending-payment/', get_approved_bookings, name='approved-bookings'),
    path('influencer/dashboard/', influencer_dashboard, name='influencer-dashboard'),
    path('influencer/bookings/', influencer_bookings, name='influencer-bookings'),
    path('influencer/dashboard/stats/', influencer_dashboard_stats, name='influencer-dashboard-stats'),
    path('debug/influencers/', debug_influencers, name='debug-influencers'),
    path('influencers/profile/setup/', influencer_profile_setup, name='influencer-profile-setup'),
    path('influencers/profile/status/', influencer_profile_status, name='influencer-profile-status'),
    path('test/', test_api, name='test-api'),
    path('influencers/my-profile/', influencer_my_profile, name='influencer-my-profile'),
    path('influencers/profile/update/', influencer_profile_update, name='influencer-profile-update'),
    path('test-auth/', test_auth, name='test-auth'),
    path('influencer/campaigns/', influencer_campaigns, name='influencer-campaigns'),
    path('influencer/campaigns/<int:campaign_id>/accept/', accept_campaign, name='accept-campaign'),
    path('influencer/campaigns/<int:campaign_id>/decline/', decline_campaign, name='decline-campaign'),
    path('influencer/campaigns/<int:campaign_id>/assets/', campaign_assets, name='campaign-assets'),
    path('quick-add-influencer/', quick_add_influencer, name='quick-add-influencer'),
    path('auth/admin-login/', admin_login_view, name='admin-login'),
    path('admin/upload-influencers-excel/', upload_influencers_excel, name='upload-influencers-excel'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
