# Generated by Django 5.1.6 on 2025-02-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_campaign_demographics_influencer_demography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='demographics',
        ),
        migrations.AddField(
            model_name='campaign',
            name='demography',
            field=models.CharField(default='18-24', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='industry',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='region',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
    ]
