# Generated by Django 5.1.6 on 2025-02-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_remove_campaign_demographics_campaign_demography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='platforms',
            field=models.JSONField(default=list),
        ),
    ]
