# Generated by Django 5.1.6 on 2025-02-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_campaign_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='social_media_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='niche',
            field=models.CharField(max_length=255),
        ),
    ]
