# Generated by Django 5.1.6 on 2025-02-22 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_influencernotification_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='total_engagements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_reach',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CampaignMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('platform', models.CharField(max_length=50)),
                ('daily_reach', models.IntegerField(default=0)),
                ('daily_engagements', models.IntegerField(default=0)),
                ('daily_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencers.campaign')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date', 'platform')},
            },
        ),
    ]
