# Generated by Django 5.1.6 on 2025-02-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0008_campaign_total_engagements_campaign_total_reach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='region',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='demography',
            field=models.CharField(default='18-24', max_length=50),
        ),
    ]
