# Generated by Django 5.1.6 on 2025-02-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0009_influencer_region_alter_influencer_demography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='total_reach',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='region',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_engagements',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='demography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CampaignMetrics',
        ),
    ]
