# Generated by Django 5.1.6 on 2025-02-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0010_remove_campaign_total_reach_remove_influencer_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='total_engagements',
        ),
        migrations.AddField(
            model_name='influencer',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
