# Generated by Django 5.1.6 on 2025-02-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='region',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='niche',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='platform',
            field=models.CharField(choices=[('X', 'X (Twitter)'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('Reddit', 'Reddit'), ('YouTube', 'YouTube')], max_length=50),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='influencer_profiles/'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='social_media_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
