# Generated by Django 5.1.6 on 2025-02-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0014_influencer_region_alter_influencer_niche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='demography',
        ),
        migrations.AddField(
            model_name='influencer',
            name='demographics',
            field=models.CharField(choices=[('13-17', '13-17'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55+', '55+')], default='18-24', max_length=20),
        ),
    ]
