# Generated by Django 5.1.6 on 2025-02-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0015_remove_influencer_demography_influencer_demographics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='demographics',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='region',
        ),
        migrations.AddField(
            model_name='influencer',
            name='demography',
            field=models.CharField(blank=True, choices=[('13-17', '13-17'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45+', '45+')], default='18-24', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='niche',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='platform',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='social_media_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
