# Generated by Django 5.1.6 on 2025-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0017_influencer_region_alter_influencer_demography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='platform',
            field=models.CharField(choices=[('X', 'X (Twitter)'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('YouTube', 'YouTube')], max_length=50),
        ),
    ]
