# Generated by Django 5.1.6 on 2025-02-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0018_alter_influencer_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum fee for booking this influencer', max_digits=10),
        ),
    ]
