# Generated by Django 5.1.6 on 2025-02-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0019_influencer_base_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
    ]
