# Generated by Django 5.1.6 on 2025-03-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0022_influencer_user'),
        ('influencers', 'add_social_platforms'),
    ]

    operations = [
    ]
