# Generated by Django 5.1.6 on 2025-03-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0023_merge_0022_influencer_user_add_social_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('YouTube', 'YouTube'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook')], max_length=50),
        ),
    ]
