# Generated by Django 5.1.6 on 2025-03-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0024_influencer_bio_alter_influencer_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
