# Generated by Django 5.1.6 on 2025-03-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0025_booking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='platforms_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
